### ISSUE TITLE
tip dating tutorial gives 404

### ISSUE THREAD

**Issue by bomeara** [revbayes/revbayes_tutorial#2]
https://github.com/revbayes/revbayes_tutorial/raw/master/tutorial_TeX/RB_DivergenceTime_TipDating_Tutorial/RB_DivergenceTime_TipDating_Tutorial.pdf gives a 404 error (linked to from http://revbayes.github.io/tutorials.html).

**Comment by wrightaprilm** [comment]
Hi @bomeara, Thanks for spotting this. This tutorial has been orphaned, as it was folded in to the Fossilized Birth-Death tutorial, a couple lines down from it. If it seems good to you, @hoehna, I'll go ahead and take this one off the tutorial roster.

**Comment by hoehna** [comment]
Yes, sounds fine with me!


Sebastian

**Comment by wrightaprilm** [comment]
Resolved via [commit](https://github.com/revbayes/revbayes.github.io/commit/0012d994af616cb179c4087a8507eb13855fa68c) to website repository.
